angular.module('detective', [
    "angularFileUpload"
    "monospaced.elastic"
    "ngProgressLite"
    "sun.scrollable"
    "truncate"
    "ui.bootstrap"
    'angulartics'
    'angulartics.google.analytics'
    'ng-embedly'
    'ngAnimate'
    'ngCookies'
    'ngResource'
    'ngSanitize'
    'textAngular'
    'ui.router'
    'ui.validate'
    'LocalStorageModule'
])